"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { isElectron } from "@/lib/utils/env";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { animate, stagger } from "animejs";
import {
  ArrowRight,
  Play,
  Check,
  CheckCircle2,
  TrendingUp,
  Cpu,
  Brain,
  Shield,
  Layers,
  ChevronRight,
  Sparkles,
  Zap,
  Clock,
  Activity,
  Globe,
  Settings,
  Mail,
  Smartphone,
  ShieldCheck,
  Lock
} from "lucide-react";

import CommandCenter from "@/components/home/CommandCenter";
import FeatureWorkforce from "@/components/home/FeatureWorkforce";
import FeatureCommerce from "@/components/home/FeatureCommerce";
import FeatureReplay from "@/components/home/FeatureReplay";
import FeaturePromptBusiness from "@/components/home/FeaturePromptBusiness";
import NeuralBackground from "@/components/home/NeuralBackground";
import { RearvyLogo } from "@/components/brand/rearvy-logo";
import { SlidingNumber } from "@/components/ui/sliding-number";

const NAV_LINKS = [
  { href: "#features", label: "Product" },
  { href: "#agents", label: "Agents" },
  { href: "#integrations", label: "Integrations" },
  { href: "#pricing", label: "Pricing" },
  { href: "/docs", label: "Resources" }
];

const INTEGRATIONS = [
  { name: "Shopify", logo: "/file.svg" },
  { name: "Stripe", logo: "/file.svg" },
  { name: "Meta", logo: "/file.svg" },
  { name: "TikTok", logo: "/file.svg" },
  { name: "Gmail", logo: "/file.svg" },
  { name: "Google Analytics", logo: "/file.svg" },
  { name: "Slack", logo: "/file.svg" },
  { name: "YouTube", logo: "/file.svg" },
  { name: "HubSpot", logo: "/file.svg" }
];

const STATS = [
  {
    value: "$12M+",
    numericValue: 12,
    prefix: "$",
    suffix: "M+",
    label: "Automated Revenue",
    detail: "Generated by AI agents",
    icon: Zap
  },
  {
    value: "94%",
    numericValue: 94,
    prefix: "",
    suffix: "%",
    label: "Operational Accuracy",
    detail: "Tasks completed successfully",
    icon: CheckCircle2
  },
  {
    value: "30K+",
    numericValue: 30,
    prefix: "",
    suffix: "K+",
    label: "Autonomous Tasks / Day",
    detail: "Across all connected systems",
    icon: Cpu
  },
  {
    value: "2.1 hrs",
    numericValue: 2.1,
    prefix: "",
    suffix: " hrs",
    decimalPlaces: 1,
    label: "Average Response Time",
    detail: "From insight to action",
    icon: Clock
  }
];

export default function LandingPage() {
  const router = useRouter();
  const [scrolled, setScrolled] = useState(false);
  const [ctaCoords, setCtaCoords] = useState({ x: 0, y: 0 });
  const [ctaHovered, setCtaHovered] = useState(false);

  const handleCtaMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    setCtaCoords({
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    });
  };

  useEffect(() => {
    if (isElectron()) {
      router.replace("/login");
    }
  }, [router]);

  // Handle scroll backdrop transition
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 30) {
        setScrolled(true);
      } else {
        setScrolled(false);
      }
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Anime.js Homepage Stagger Entrance
  useEffect(() => {
    // 1. Title stagger fade in
    animate(".anime-hero-fade", {
      opacity: [0, 1],
      translateY: [25, 0],
      delay: stagger(100, { start: 100 }),
      ease: "outExpo",
      duration: 1000
    });

    // 2. CommandCenter fade/slide
    animate(".anime-hero-visual", {
      opacity: [0, 1],
      scale: [0.97, 1],
      translateY: [30, 0],
      delay: 500,
      ease: "outExpo",
      duration: 1200
    });

    // 3. Integrations tags slide
    animate(".anime-integration-logo", {
      opacity: [0, 0.5],
      scale: [0.9, 1],
      delay: stagger(50, { start: 800 }),
      ease: "outExpo",
      duration: 800
    });

    // 4. Stats cards staggered lift
    animate(".anime-stat-card", {
      opacity: [0, 1],
      translateY: [25, 0],
      delay: stagger(80, { start: 1100 }),
      ease: "outExpo",
      duration: 900
    });

    // 5. Grid blocks load
    animate(".anime-feature-block", {
      opacity: [0, 1],
      translateY: [30, 0],
      delay: stagger(100, { start: 1400 }),
      ease: "outExpo",
      duration: 1000
    });
  }, []);

  return (
    <div className="dark min-h-screen bg-black text-white selection:bg-emerald-500 selection:text-black antialiased font-sans relative overflow-x-hidden">
      
      {/* Background Neural Grid and Particle overlay */}
      <div className="absolute inset-0 z-0 neural-grid pointer-events-none opacity-40" />
      <div className="absolute inset-0 z-0 particle-field pointer-events-none" />
      <NeuralBackground />

      {/* Cinematic Ambient Glow Orbs */}
      <div className="absolute top-[8%] left-[20%] w-[450px] h-[450px] bg-emerald-500/5 rounded-full blur-[140px] pointer-events-none z-0" />
      <div className="absolute top-[20%] right-[10%] w-[550px] h-[550px] bg-teal-500/5 rounded-full blur-[150px] pointer-events-none z-0" />

      {/* Minimal Futuristic Navbar */}
      <header className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 border-b ${
        scrolled 
          ? "border-white/5 bg-black/85 backdrop-blur-md py-3 shadow-[0_4px_30px_rgba(0,0,0,0.5)]" 
          : "border-transparent bg-transparent py-5"
      }`}>
        <div className="mx-auto flex max-w-7xl items-center justify-between px-4 sm:px-6">
          {/* Logo */}
          <Link href="/" className="flex items-center gap-1.5 transition-transform hover:scale-102">
            <RearvyLogo
              priority
              markSize={32}
              className="text-white"
              markClassName="h-8 w-8"
              textClassName="text-[20px] font-extrabold"
            />
          </Link>

          {/* Navigation Links */}
          {!isElectron() && (
            <nav className="hidden md:flex items-center gap-8 text-[13px] font-semibold text-white/50">
              {NAV_LINKS.map((link) => (
                <Link 
                  key={link.href} 
                  href={link.href} 
                  className="transition-colors hover:text-white relative py-1 group"
                >
                  {link.label}
                  <span className="absolute bottom-0 left-0 w-0 h-[1.5px] bg-emerald-400 transition-all duration-300 group-hover:w-full" />
                </Link>
              ))}
            </nav>
          )}

          {/* Actions */}
          <div className="flex items-center gap-4">
            <Link href="/login">
              <Button 
                variant="ghost" 
                size="sm" 
                className="text-white/60 hover:text-white hover:bg-white/5 text-[13px] font-bold px-4"
              >
                Sign in
              </Button>
            </Link>
            <Link href="/signup">
              <Button 
                size="sm" 
                className="bg-emerald-500 hover:bg-emerald-400 text-black font-extrabold text-[12px] px-4.5 py-2.5 rounded-lg shadow-[0_0_20px_rgba(16,185,129,0.35)] transition-all hover:scale-[1.02] flex items-center gap-1"
              >
                Start Free <ArrowRight size={13} />
              </Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="relative z-10 pt-28 lg:pt-36">
        
        {/* ========================================================================= */}
        {/* HERO SECTION */}
        {/* ========================================================================= */}
        <section className="relative isolate px-4 sm:px-6">
          <div className="mx-auto max-w-7xl grid gap-16 lg:grid-cols-[0.9fr_1.1fr] lg:items-center">
            
            {/* Left Column: Copy blocks */}
            <div className="space-y-7 text-left max-w-xl relative z-10">
              
              {/* OS Badge */}
              <div className="anime-hero-fade opacity-0 inline-flex items-center gap-1.5 rounded-full border border-emerald-500/25 bg-emerald-500/5 px-4 py-1.5 text-[10.5px] font-black text-emerald-400 tracking-wider uppercase">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
                Autonomous Business OS
              </div>

              {/* Huge Headlines */}
              <div className="space-y-4">
                <h1 className="anime-hero-fade opacity-0 text-5xl font-black tracking-tight text-white sm:text-6xl lg:text-[70px] leading-[1.04]">
                  Describe a business. <br />
                  <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-emerald-500 bg-clip-text text-transparent drop-shadow-[0_0_20px_rgba(16,185,129,0.2)]">
                    Rearvy runs it.
                  </span>
                </h1>
                
                <p className="anime-hero-fade opacity-0 text-sm leading-relaxed text-white/50 max-w-md font-medium">
                  The world's first AI operating system that builds, operates, and scales your business using autonomous agents. Connect systems, prompt your goal, and watch execution happen.
                </p>
              </div>

              {/* CTAs */}
              <div className="anime-hero-fade opacity-0 flex flex-wrap gap-4 pt-2">
                <Link href="/signup">
                  <Button 
                    size="lg" 
                    className="h-12 bg-emerald-500 hover:bg-emerald-400 text-black font-extrabold shadow-[0_0_30px_rgba(16,185,129,0.4)] px-7 transition-all flex items-center gap-1.5 hover:scale-[1.02]"
                  >
                    Start Free <ArrowRight size={16} />
                  </Button>
                </Link>
                <Link href="/demo">
                  <Button 
                    size="lg" 
                    variant="outline" 
                    className="h-12 border-white/10 bg-white/5 px-6 text-white/80 hover:bg-white/10 hover:text-white transition-all flex items-center gap-2"
                  >
                    <Play size={14} fill="currentColor" /> Watch Live Demo
                  </Button>
                </Link>
              </div>

              {/* Three trust check points */}
              <div className="anime-hero-fade opacity-0 flex flex-wrap gap-x-6 gap-y-2 pt-6 border-t border-white/5 text-[11px] text-white/40 font-bold uppercase tracking-wider">
                <div className="flex items-center gap-1.5">
                  <CheckCircle2 size={13} className="text-emerald-400" />
                  <span>No credit card required</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <Zap size={13} className="text-emerald-400" />
                  <span>Setup in 2 minutes</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <ShieldCheck size={13} className="text-emerald-400" />
                  <span>Cancel anytime</span>
                </div>
              </div>

            </div>

            {/* Right Column: High-Fidelity Command Center dashboard visual with floating overlays */}
            <div className="anime-hero-visual opacity-0 w-full flex justify-center lg:justify-end relative z-10">
              <div className="h-[440px] w-full max-w-[620px] sm:h-[480px] md:h-[520px] lg:h-auto lg:aspect-[1.12/1]">
                <CommandCenter />
              </div>
            </div>

          </div>

          {/* Apple-level Cinematic planet glow bottom backdrop curve */}
          <div className="absolute left-[50%] bottom-[-24%] transform -translate-x-1/2 w-[140%] h-[300px] rounded-[100%] bg-gradient-to-t from-emerald-500/10 via-black to-black z-[-1] pointer-events-none border-t border-emerald-500/20" />
        </section>

        {/* ========================================================================= */}
        {/* TRUST / INTEGRATION BAR */}
        {/* ========================================================================= */}
        <section id="integrations" className="border-y border-white/5 bg-white/[0.002] py-9 mt-28 overflow-hidden relative z-10">
          <div className="absolute inset-y-0 left-0 w-36 bg-gradient-to-r from-black to-transparent z-10" />
          <div className="absolute inset-y-0 right-0 w-36 bg-gradient-to-l from-black to-transparent z-10" />

          <div className="mx-auto max-w-7xl px-4 sm:px-6">
            <div className="text-center mb-6">
              <p className="text-[10px] font-black uppercase tracking-[0.3em] text-white/30">
                NATIVE INTEGRATIONS
              </p>
            </div>

            {/* Scrolling list */}
            <div className="flex justify-center items-center py-2 px-10 gap-x-10 lg:gap-x-14 flex-wrap z-10 relative">
              {INTEGRATIONS.map((integration, idx) => (
                <div 
                  key={idx} 
                  className="anime-integration-logo opacity-0 flex items-center gap-2 text-white/40 hover:text-white/80 cursor-default transition-colors"
                >
                  <span className="font-semibold text-[13px] tracking-tight">{integration.name}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ========================================================================= */}
        {/* STATS SECTION */}
        {/* ========================================================================= */}
        <section className="px-4 py-20 sm:px-6 max-w-7xl mx-auto relative z-10">
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {STATS.map((stat, index) => {
              const Icon = stat.icon;
              return (
                <div 
                  key={index} 
                  className="anime-stat-card opacity-0 rounded-2xl border border-white/5 bg-gradient-to-b from-white/[0.015] to-transparent p-6 shadow-xl hover:border-emerald-500/20 transition-all duration-300 group relative overflow-hidden"
                >
                  {/* Subtle corner light reflection */}
                  <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-emerald-500/5 to-transparent rounded-tr-2xl group-hover:opacity-100 opacity-40 transition-opacity" />
                  
                  <div className="flex justify-between items-center">
                    <div className="text-3xl font-black tracking-tight text-white">
                      {stat.numericValue !== undefined ? (
                        <span className="inline-flex items-center">
                          <span>{stat.prefix}</span>
                          <SlidingNumber 
                            number={stat.numericValue} 
                            fromNumber={0} 
                            decimalPlaces={stat.decimalPlaces ?? 0}
                            inView={true} 
                            initiallyStable={false} 
                            transition={{ stiffness: 90, damping: 15, mass: 0.5 }}
                          />
                          <span>{stat.suffix}</span>
                        </span>
                      ) : (
                        stat.value
                      )}
                    </div>
                    <div className="text-emerald-400 p-2 rounded-lg bg-emerald-500/5 border border-emerald-500/10">
                      <Icon size={16} />
                    </div>
                  </div>

                  <div className="text-[12px] font-black text-white/90 mt-4 uppercase tracking-wider">
                    {stat.label}
                  </div>
                  <p className="text-[10px] text-white/40 mt-1 font-medium">
                    {stat.detail}
                  </p>
                </div>
              );
            })}
          </div>
        </section>

        {/* ========================================================================= */}
        {/* FEATURE SECTIONS ("Built for the future of business") */}
        {/* ========================================================================= */}
        <section id="features" className="px-4 py-24 sm:px-6 max-w-7xl mx-auto relative z-10">
          <div className="space-y-16">
            
            {/* Title blocks */}
            <div className="text-center max-w-xl mx-auto space-y-4">
              <h2 className="text-3xl font-black tracking-tight sm:text-4xl">
                Built for the future of business
              </h2>
              <p className="text-sm text-white/40 leading-relaxed font-semibold">
                An AI workforce that thinks, plans, and executes — so you can focus on growth.
              </p>
            </div>

            {/* 4 Feature Cards Grid Mockups */}
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
              
              {/* Card 1: AI Workforce */}
              <div className="anime-feature-block opacity-0 rounded-2xl border border-white/5 bg-[#050505]/60 p-6 flex flex-col justify-between hover:border-emerald-500/10 transition-colors shadow-xl group">
                <div className="space-y-2">
                  <h3 className="text-base font-black text-white group-hover:text-emerald-400 transition-colors">AI Workforce</h3>
                  <p className="text-[11px] text-white/40 leading-relaxed font-semibold">
                    Autonomous agents that research, plan, and execute complex tasks across your entire business.
                  </p>
                </div>
                <div className="mt-8 flex justify-center">
                  <FeatureWorkforce />
                </div>
              </div>

              {/* Card 2: Autonomous Commerce */}
              <div className="anime-feature-block opacity-0 rounded-2xl border border-white/5 bg-[#050505]/60 p-6 flex flex-col justify-between hover:border-emerald-500/10 transition-colors shadow-xl group">
                <div className="space-y-2">
                  <h3 className="text-base font-black text-white group-hover:text-emerald-400 transition-colors">Autonomous Commerce</h3>
                  <p className="text-[11px] text-white/40 leading-relaxed font-semibold">
                    From product research to order fulfillment, Rearvy handles the entire commerce engine.
                  </p>
                </div>
                <div className="mt-8 flex justify-center">
                  <FeatureCommerce />
                </div>
              </div>

              {/* Card 3: Operations Replay */}
              <div className="anime-feature-block opacity-0 rounded-2xl border border-white/5 bg-[#050505]/60 p-6 flex flex-col justify-between hover:border-emerald-500/10 transition-colors shadow-xl group">
                <div className="space-y-2">
                  <h3 className="text-base font-black text-white group-hover:text-emerald-400 transition-colors">Operations Replay</h3>
                  <p className="text-[11px] text-white/40 leading-relaxed font-semibold">
                    Watch every action, decision, and execution your AI agents perform — in real time or anytime.
                  </p>
                </div>
                <div className="mt-8 flex justify-center">
                  <FeatureReplay />
                </div>
              </div>

              {/* Card 4: Prompt Driven Business */}
              <div className="anime-feature-block opacity-0 rounded-2xl border border-white/5 bg-[#050505]/60 p-6 flex flex-col justify-between hover:border-emerald-500/10 transition-colors shadow-xl group">
                <div className="space-y-2">
                  <h3 className="text-base font-black text-white group-hover:text-emerald-400 transition-colors">Prompt Driven Business</h3>
                  <p className="text-[11px] text-white/40 leading-relaxed font-semibold">
                    Describe what you want. Rearvy handles the rest.
                  </p>
                </div>
                <div className="mt-8 flex justify-center">
                  <FeaturePromptBusiness />
                </div>
              </div>

            </div>

          </div>
        </section>

        {/* ========================================================================= */}
        {/* FINAL CTA BANNER */}
        {/* ========================================================================= */}
        <section className="px-4 py-28 sm:px-6 relative overflow-hidden">
          {/* Deep ambient glow layers behind the card */}
          <div className="absolute top-1/2 left-1/3 -translate-y-1/2 w-[450px] h-[450px] bg-emerald-500/10 rounded-full blur-[140px] pointer-events-none" />
          <div className="absolute top-1/2 right-1/3 -translate-y-1/2 w-[450px] h-[450px] bg-indigo-500/10 rounded-full blur-[140px] pointer-events-none" />
          
          {/* Card Wrapper with shifting gradient border */}
          <div className="mx-auto max-w-5xl rounded-[32px] p-[1px] bg-gradient-to-b from-white/10 via-emerald-500/20 to-white/5 relative group transition-all duration-700 hover:from-emerald-500/40 hover:via-teal-400/30 hover:to-indigo-500/30 shadow-[0_0_50px_rgba(0,0,0,0.85)]">
            <div 
              onMouseMove={handleCtaMouseMove}
              onMouseEnter={() => setCtaHovered(true)}
              onMouseLeave={() => setCtaHovered(false)}
              className="w-full rounded-[31px] bg-[#020202] p-12 lg:py-20 lg:px-24 text-center relative overflow-hidden flex flex-col items-center justify-center"
            >
              {/* Styles for scan, shimmer and float animations */}
              <style dangerouslySetInnerHTML={{__html: `
                @keyframes float-badge {
                  0%, 100% { transform: translateY(0); }
                  50% { transform: translateY(-8px); }
                }
                .animate-float-badge-1 { animation: float-badge 6s ease-in-out infinite; }
                .animate-float-badge-2 { animation: float-badge 8s ease-in-out infinite 1s; }
                .animate-float-badge-3 { animation: float-badge 7s ease-in-out infinite 0.5s; }
                .animate-float-badge-4 { animation: float-badge 5s ease-in-out infinite 1.5s; }
                
                @keyframes cta-scan {
                  0% { transform: translateY(-250px); opacity: 0; }
                  10% { opacity: 0.3; }
                  90% { opacity: 0.3; }
                  100% { transform: translateY(350px); opacity: 0; }
                }
                .animate-cta-scan { animation: cta-scan 10s linear infinite; }

                @keyframes scroll-logs {
                  0% { transform: translateY(0); }
                  100% { transform: translateY(-50%); }
                }
                @keyframes scroll-logs-reverse {
                  0% { transform: translateY(-50%); }
                  100% { transform: translateY(0); }
                }
                .animate-scroll-logs { animation: scroll-logs 20s linear infinite; }
                .animate-scroll-logs-reverse { animation: scroll-logs-reverse 24s linear infinite; }

                @keyframes shimmer {
                  100% { transform: translateX(100%); }
                }
              `}} />

              {/* Glowing scanline sweep */}
              <div className="absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-emerald-500/20 to-transparent animate-cta-scan pointer-events-none" />

              {/* Terminal window header */}
              <div className="absolute top-0 left-0 right-0 h-11 border-b border-white/5 bg-white/[0.02] flex items-center justify-between px-6 pointer-events-none select-none">
                <div className="flex items-center gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-red-500/25 border border-red-500/40" />
                  <span className="w-2.5 h-2.5 rounded-full bg-yellow-500/25 border border-yellow-500/40" />
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/25 border border-emerald-500/40" />
                </div>
                <div className="flex items-center gap-2">
                  <Lock size={10} className="text-white/20" />
                  <span className="text-[9px] font-mono tracking-wider text-white/30 font-bold uppercase">REARVY_CORE_v2.0.4 // SECURE_SHELL</span>
                </div>
                <div className="flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                  <span className="text-[8px] font-mono text-emerald-400 font-bold uppercase tracking-wider">ONLINE</span>
                </div>
              </div>

              {/* Cyber Corner Decos */}
              <div className="absolute top-16 left-6 w-3 h-3 border-t border-l border-white/20 pointer-events-none select-none" />
              <div className="absolute top-16 right-6 w-3 h-3 border-t border-r border-white/20 pointer-events-none select-none" />
              <div className="absolute bottom-6 left-6 w-3 h-3 border-b border-l border-white/20 pointer-events-none select-none" />
              <div className="absolute bottom-6 right-6 w-3 h-3 border-b border-r border-white/20 pointer-events-none select-none" />

              {/* Scrolling logs watermark background */}
              <div className="absolute inset-x-0 top-11 bottom-0 overflow-hidden opacity-[0.03] select-none pointer-events-none font-mono text-[9px] text-emerald-400 p-8 flex justify-between gap-12 text-left">
                <div className="flex flex-col gap-1.5 animate-scroll-logs">
                  <div>&gt; INITIALIZING AGENT: STRATEGY_OPTIMIZER_01</div>
                  <div>&gt; ACCESSING SHOPIFY API... SUCCESS</div>
                  <div>&gt; ANALYZING COMPETITOR ADS... DONE</div>
                  <div>&gt; GENERATING NEW CREATIVES... SUCCESS</div>
                  <div>&gt; DEPLOYING FB AD CAMPAIGN ID: 9481</div>
                  <div>&gt; EARNINGS DETECTED: +$1,240.00</div>
                  <div>&gt; REDIRECTING STRIPE PAYOUT... COMPLETE</div>
                  <div>&gt; INITIATING EMAIL OUTREACH... RUNNING</div>
                  <div>&gt; USER SESSION DETECTED // PREPARING DASHBOARD</div>
                  <div>&gt; ALL SYSTEMS OPTIMAL. READY TO SCALE.</div>
                  {/* Duplicate for infinite loop */}
                  <div>&gt; INITIALIZING AGENT: STRATEGY_OPTIMIZER_01</div>
                  <div>&gt; ACCESSING SHOPIFY API... SUCCESS</div>
                  <div>&gt; ANALYZING COMPETITOR ADS... DONE</div>
                  <div>&gt; GENERATING NEW CREATIVES... SUCCESS</div>
                  <div>&gt; DEPLOYING FB AD CAMPAIGN ID: 9481</div>
                  <div>&gt; EARNINGS DETECTED: +$1,240.00</div>
                  <div>&gt; REDIRECTING STRIPE PAYOUT... COMPLETE</div>
                  <div>&gt; INITIATING EMAIL OUTREACH... RUNNING</div>
                  <div>&gt; USER SESSION DETECTED // PREPARING DASHBOARD</div>
                  <div>&gt; ALL SYSTEMS OPTIMAL. READY TO SCALE.</div>
                </div>
                <div className="hidden md:flex flex-col gap-1.5 animate-scroll-logs-reverse">
                  <div>&gt; DEPLOYING AUTO-STORE GEN_v1.0.8</div>
                  <div>&gt; CONFIGURING PAYMENT GATEWAY (STRIPE)</div>
                  <div>&gt; IMPORTING INVENTORY MAP // 482 ITEMS</div>
                  <div>&gt; RESOLVING AD DELIVERY ERRORS // HEALED</div>
                  <div>&gt; LAUNCHING SOCIAL REELS PROCESSOR // OK</div>
                  <div>&gt; SENT SENTIMENT REPORT TO USER // 98.4% +</div>
                  <div>&gt; WALLET SYNC: 1.48 ETH ACQUIRED</div>
                  <div>&gt; BOT REPORT: 42 TASKS EXECUTED IN 5MIN</div>
                  <div>&gt; CRITICAL TASK EXECUTED: REFUND RESOLUTION</div>
                  <div>&gt; MONITORING CONVERSIONS... CURRENT RATE: 4.82%</div>
                  {/* Duplicate for infinite loop */}
                  <div>&gt; DEPLOYING AUTO-STORE GEN_v1.0.8</div>
                  <div>&gt; CONFIGURING PAYMENT GATEWAY (STRIPE)</div>
                  <div>&gt; IMPORTING INVENTORY MAP // 482 ITEMS</div>
                  <div>&gt; RESOLVING AD DELIVERY ERRORS // HEALED</div>
                  <div>&gt; LAUNCHING SOCIAL REELS PROCESSOR // OK</div>
                  <div>&gt; SENT SENTIMENT REPORT TO USER // 98.4% +</div>
                  <div>&gt; WALLET SYNC: 1.48 ETH ACQUIRED</div>
                  <div>&gt; BOT REPORT: 42 TASKS EXECUTED IN 5MIN</div>
                  <div>&gt; CRITICAL TASK EXECUTED: REFUND RESOLUTION</div>
                  <div>&gt; MONITORING CONVERSIONS... CURRENT RATE: 4.82%</div>
                </div>
              </div>

              {/* Interactive Cursor Spotlight Glow */}
              <div 
                className="absolute pointer-events-none transition-opacity duration-500"
                style={{
                  width: "480px",
                  height: "480px",
                  borderRadius: "50%",
                  background: "radial-gradient(circle, rgba(16,185,129,0.12) 0%, rgba(99,102,241,0.06) 40%, transparent 70%)",
                  left: `${ctaCoords.x - 240}px`,
                  top: `${ctaCoords.y - 240}px`,
                  opacity: ctaHovered ? 1 : 0,
                  mixBlendMode: "screen",
                }}
              />
              
              {/* Interactive Grid Mesh */}
              <div 
                className="absolute inset-0 pointer-events-none transition-opacity duration-700"
                style={{
                  backgroundImage: `
                    linear-gradient(to right, rgba(255, 255, 255, 0.015) 1px, transparent 1px),
                    linear-gradient(to bottom, rgba(255, 255, 255, 0.015) 1px, transparent 1px)
                  `,
                  backgroundSize: "32px 32px",
                  maskImage: ctaHovered 
                    ? `radial-gradient(240px circle at ${ctaCoords.x}px ${ctaCoords.y}px, black 30%, transparent)` 
                    : `radial-gradient(240px circle at 50% 50%, black 20%, transparent)`,
                  WebkitMaskImage: ctaHovered 
                    ? `radial-gradient(240px circle at ${ctaCoords.x}px ${ctaCoords.y}px, black 30%, transparent)` 
                    : `radial-gradient(240px circle at 50% 50%, black 20%, transparent)`,
                  opacity: ctaHovered ? 0.8 : 0.4,
                }}
              />

              {/* Floating system telemetry chips on the left */}
              <div className="hidden lg:flex absolute left-8 top-[28%] items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/5 backdrop-blur-sm px-3.5 py-2 text-[9px] font-mono font-bold text-emerald-400 tracking-wider uppercase animate-float-badge-1 shadow-[0_4px_12px_rgba(0,0,0,0.5)]">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
                SYS_OPS // ACTIVE [98.2%]
              </div>
              <div className="hidden lg:flex absolute left-14 bottom-[28%] items-center gap-2 rounded-full border border-white/5 bg-black/60 backdrop-blur-md px-3.5 py-2 text-[9px] font-mono font-semibold text-white/50 tracking-wider uppercase animate-float-badge-2 shadow-[0_4px_12px_rgba(0,0,0,0.5)]">
                <Cpu size={10} className="text-white/40" />
                NODES // 12_ONLINE
              </div>

              {/* Floating system telemetry chips on the right */}
              <div className="hidden lg:flex absolute right-8 top-[28%] items-center gap-2 rounded-full border border-white/5 bg-black/60 backdrop-blur-md px-3.5 py-2 text-[9px] font-mono font-semibold text-white/50 tracking-wider uppercase animate-float-badge-3 shadow-[0_4px_12px_rgba(0,0,0,0.5)]">
                <Activity size={10} className="text-emerald-400" />
                LATENCY // 42MS
              </div>
              <div className="hidden lg:flex absolute right-16 bottom-[28%] items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/5 backdrop-blur-sm px-3.5 py-2 text-[9px] font-mono font-bold text-emerald-400 tracking-wider uppercase animate-float-badge-4 shadow-[0_4px_12px_rgba(0,0,0,0.5)]">
                <ShieldCheck size={10} className="text-emerald-400" />
                SANDBOX // LOCKED
              </div>

              {/* central glowing logo removed */}

              <div className="max-w-2xl space-y-6 relative z-10 flex flex-col items-center select-none">
                <h2 className="text-3xl sm:text-4xl lg:text-[48px] font-black tracking-tight leading-[1.08] text-white">
                  The future of business <br />
                  <span className="bg-gradient-to-r from-emerald-400 via-teal-300 to-emerald-500 bg-clip-text text-transparent drop-shadow-[0_0_15px_rgba(16,185,129,0.35)]">
                    is autonomous.
                  </span>
                </h2>
                
                <p className="max-w-md text-sm text-white/50 leading-relaxed font-semibold">
                  Rearvy is not another tool. It's your AI operating system. Start building your autonomous business today.
                </p>
                
                <div className="pt-6 relative z-20">
                  <Link href="/signup">
                    <div className="relative group/btn inline-block">
                      {/* Multi-layer glowing shadow */}
                      <div className="absolute -inset-1 bg-gradient-to-r from-emerald-500 via-teal-400 to-indigo-500 rounded-xl blur-lg opacity-30 group-hover/btn:opacity-75 transition-opacity duration-500 animate-pulse" />
                      <Button 
                        size="lg" 
                        className="relative bg-gradient-to-r from-emerald-500 via-teal-400 to-emerald-500 bg-[length:200%_auto] hover:bg-[position:right_center] text-black font-extrabold px-10 h-13 rounded-xl transition-all duration-500 flex items-center gap-2 shadow-[0_0_30px_rgba(16,185,129,0.35)] hover:scale-[1.03] overflow-hidden cursor-pointer"
                      >
                        {/* Shimmer sweep */}
                        <span className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/25 to-transparent -translate-x-full group-hover/btn:animate-[shimmer_1.5s_ease-in-out_infinite]" />
                        
                        Start Free 
                        <ArrowRight size={16} className="transition-transform group-hover/btn:translate-x-1.5" />
                      </Button>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>

      </main>

      {/* ========================================================================= */}
      {/* FOOTER */}
      {/* ========================================================================= */}
      <footer className="border-t border-white/5 bg-black py-12 text-[11px] text-white/40 relative z-10 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 sm:px-6 md:flex-row md:items-center md:justify-between">
          <div className="flex flex-col gap-2">
            <div className="flex items-center gap-1.5">
              <span className="text-[14px] font-black text-emerald-400 font-mono">R</span>
              <span className="font-bold text-white">Rearvy</span>
            </div>
            <p className="text-[10.5px]">The autonomous operating system for internet business.</p>
          </div>

          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 font-bold uppercase tracking-wider">
            <Link href="/docs" className="hover:text-white transition-colors">Docs</Link>
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
            <Link href="/security" className="hover:text-white transition-colors">Security</Link>
          </div>
        </div>
      </footer>

    </div>
  );
}
