/**
 * AI Brain — Orchestration & Planning Types
 *
 * These types define the core data structures for the AI Brain's planning
 * and orchestration layer. They are used across plan generation, step execution,
 * the orchestration API, and the Firestore task store.
 */

// ---------------------------------------------------------------------------
// Step Types
// ---------------------------------------------------------------------------

/**
 * The type of work a step performs.
 * Each maps to one or more existing Rearvy tool implementations.
 */
export type OrchestratorStepType =
  | "web_research"      // → lib/ai/tools/web.ts
  | "browser_task"      // → lib/ai/tools/browser.ts
  | "email_draft"       // → lib/ai/tools/gmail.ts
  | "memory_recall"     // → lib/ai/tools/memories.ts
  | "memory_save"       // → lib/ai/tools/memories.ts
  | "data_analysis"     // → model-router deep_business_reasoning task
  | "document_generate" // → lib/ai/document-generation.ts
  | "media_generate"    // → lib/ai/tools/media.ts
  | "desktop_workflow"  // → lib/ai/tools/desktop-automation.ts
  | "terminal_command"  // → lib/ai/tools/terminal.ts
  | "llm_reasoning"     // → direct generateText call with deep_business_reasoning
  | "user_approval";    // → askUser tool pattern (pauses for human confirmation)

/** Lifecycle status of a single orchestration step. */
export type OrchestratorStepStatus =
  | "pending"
  | "running"
  | "done"
  | "failed"
  | "skipped"
  | "awaiting_approval";

/**
 * A single unit of work within an orchestration plan.
 * Steps may declare dependencies on prior step IDs to enforce ordering.
 */
export interface OrchestratorStep {
  /** Stable identifier for this step within the plan (e.g. "step_1"). */
  id: string;

  /** Human-readable name shown in UI progress events. */
  name: string;

  /** Detailed description of what this step will do. */
  description: string;

  /** The type of work. Determines which existing tool handles execution. */
  type: OrchestratorStepType;

  /**
   * Step-specific input parameters.
   * Shape varies by type — e.g. web_research gets { query }, email_draft gets { to, subject }.
   */
  input: Record<string, unknown>;

  /**
   * IDs of steps that must complete before this step begins.
   * Empty array means the step can start immediately.
   */
  dependencies: string[];

  /** Current lifecycle status. Starts as "pending". */
  status: OrchestratorStepStatus;

  /**
   * Whether this step requires explicit user approval before it runs.
   * Always true for: email sends, terminal commands, desktop automation,
   * financial actions, and any step the model flags as sensitive.
   */
  requiresApproval: boolean;

  /** ISO timestamp of when the step started. */
  startedAt?: string | null;

  /** ISO timestamp of when the step completed or failed. */
  finishedAt?: string | null;

  /** Output from step execution. Shape varies by step type. */
  result?: unknown;

  /** Error detail if the step failed. */
  error?: string | null;
}

// ---------------------------------------------------------------------------
// Plan Types
// ---------------------------------------------------------------------------

/**
 * A complete orchestration plan generated by the AI Brain.
 *
 * The model is required to output `assumptions[]` and a `confidence_score`
 * before any steps run. This enables the confidence gate to pause
 * low-confidence plans for user review before execution begins.
 */
export interface OrchestratorPlan {
  /**
   * The goal this plan was generated to achieve.
   * Mirrors the user's original request.
   */
  goal: string;

  /**
   * Things the model assumed to be true in order to generate this plan.
   * The user should confirm these before high-stakes execution begins.
   * Minimum 1 assumption required.
   */
  assumptions: string[];

  /**
   * Model confidence that the plan is correct and achievable (0.0–1.0).
   * Plans below the CONFIDENCE_GATE_THRESHOLD require user approval.
   */
  confidence_score: number;

  /**
   * Ordered list of steps to execute.
   * Steps with dependencies will be sequenced automatically.
   */
  steps: OrchestratorStep[];

  /**
   * Whether any step in the plan requires explicit user approval.
   * Computed from step.requiresApproval OR confidence_score < threshold.
   */
  requires_approval: boolean;

  /** Rough estimated total duration in milliseconds. */
  estimated_duration_ms: number;

  /**
   * Short summary of the plan shown to users before they approve execution.
   * Max 200 characters.
   */
  summary: string;
}

// ---------------------------------------------------------------------------
// Confidence Gate
// ---------------------------------------------------------------------------

/**
 * Configuration for the confidence gate.
 * Plans below the threshold are paused pending user approval via askUser.
 */
export interface ConfidenceGateConfig {
  /** Confidence score below which the plan requires approval (default: 0.7). */
  threshold: number;

  /**
   * Step types that ALWAYS require approval regardless of confidence score.
   * These are irreversible or high-risk operations.
   */
  alwaysRequireApprovalFor: OrchestratorStepType[];
}

/** Default confidence gate configuration. */
export const DEFAULT_CONFIDENCE_GATE: ConfidenceGateConfig = {
  threshold: 0.7,
  alwaysRequireApprovalFor: [
    "email_draft",
    "terminal_command",
    "desktop_workflow",
    "user_approval",
  ],
};

// ---------------------------------------------------------------------------
// Firestore Task Document
// ---------------------------------------------------------------------------

/** Top-level status of an orchestration task persisted in Firestore. */
export type OrchestratorTaskStatus =
  | "planning"
  | "awaiting_approval"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

/**
 * Firestore document shape for a persisted orchestration task.
 * Stored in the `orchestration_tasks` collection.
 * All queries are scoped by `user_id` for multi-tenant isolation.
 */
export interface OrchestratorTask {
  /** Firestore document ID. */
  id: string;

  /** Firebase Auth UID. Every query must be scoped to this. */
  user_id: string;

  /** Linked chat session where the orchestration was triggered. */
  chat_id: string;

  /** Optional project context. */
  project_id: string | null;

  /** The original user goal. */
  goal: string;

  /** Top-level lifecycle status. */
  status: OrchestratorTaskStatus;

  /**
   * The generated plan. Null during the `planning` phase
   * before the model has responded.
   */
  plan: OrchestratorPlan | null;

  /**
   * Live step states. Written incrementally as execution progresses.
   * Keyed by step ID for O(1) lookup.
   */
  step_states: Record<string, OrchestratorStep>;

  /** Error message if the task reached `failed` status. */
  error: string | null;

  /** ISO timestamp when the task was created. */
  created_at: string;

  /** ISO timestamp of the last state update. */
  updated_at: string;

  /** ISO timestamp when execution completed (success or failure). */
  finished_at: string | null;
}

// ---------------------------------------------------------------------------
// SSE Event Types (streamed from /api/ai/orchestrate)
// ---------------------------------------------------------------------------

/** Discriminated union of all events streamed from the orchestration endpoint. */
export type OrchestrationEvent =
  | { event: "plan_generated"; plan: OrchestratorPlan; task_id: string }
  | { event: "step_started"; step_id: string; step_name: string; task_id: string }
  | { event: "step_done"; step_id: string; step_name: string; result: unknown; task_id: string }
  | { event: "step_failed"; step_id: string; step_name: string; error: string; task_id: string }
  | { event: "approval_required"; task_id: string; reason: string; plan: OrchestratorPlan }
  | { event: "orchestration_complete"; task_id: string; summary: string; steps_completed: number; steps_failed: number }
  | { event: "orchestration_error"; task_id: string; error: string };
